### ISSUE TITLE
SRT parsing issue

### ISSUE THREAD

**Issue by oytuntez** [captioning/captioning#10]
Hello again!

We encountered an issue when getting cues of an SRT file. Example file: https://gist.github.com/oytuntez/781a61e82dcd552de7cf

```php
$file = new SubripFile(parent::getFilePath());

foreach ($file->getCues() as $line) {
echo $line->getText();
}
```

Very weirdly, 8th segment, whose text is ```<i>DejaVu Sans Oblique</i>``` is actually coming together with the next segment. On the 8th iteration, this would echo this:

```
<i>DejaVu Sans Oblique</i>

9
00:00:39,812 --> 00:00:45,745
[de.derhess.video.vimeo]
http://blog.derhess.de
```

While it should echo this only:
```
<i>DejaVu Sans Oblique</i>
```

**Comment by oytuntez** [comment]
Alright, investigated the issue little bit better. It appears there is a whitespace on the line before "9". Below is a screenshot, which put that line and the next segment together, until a proper new segment line ("10") is found.

I'm not sure if this is an issue on our side or the file. What do you think? Should we ignore white lines, any idea what the spec says?

![Screenshot]
(http://i.snag.gy/CsCmd.jpg)

**Comment by delphiki** [comment]
Hello !

From what I read, there should be a blank line (no space, no tab) between each cues.
See here:
- https://wiki.videolan.org/SubRip/
- http://matroska.org/technical/specs/subtitles/srt.html

I couldn't find any official spec.
That's how I parse the subrip files anyway.

How did you generate your file?

**Comment by oytuntez** [comment]
Sorry, I must have forgotten your reply. You are right, there must only be a blank line, no other whitespace elements. So that was the issue of the file, not this package.

Thanks!
