### ISSUE TITLE
WebVTT parser does not support mm:ss.ttt timestamp format

### ISSUE THREAD

**Issue by hartman** [captioning/captioning#25]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Video_Text_Tracks_Format

> The timestamps must be in one of two formats:
> mm:ss.ttt
> hh:mm:ss.ttt

Example file: http://www.videojs.com/vtt/captions.vtt

**Comment by delphiki** [comment]
It's been a while since the last time I checked the WebVTT spec, so thanks for pointing those out (this one and https://github.com/captioning/captioning/issues/26).

Will try to fix this ASAP.

**Comment by delphiki** [comment]
Actually, this has already been fixed by @RamanYeda in PR #18
