### ISSUE TITLE
WebVTT parser does not support optional text headers

### ISSUE THREAD

**Issue by hartman** [captioning/captioning#26]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Video_Text_Tracks_Format

> An optional text header to the right of WEBVTT.
> * There must be at least one space after WEBVTT
> * You might use this to add a description to the file
> * You may use anything except newlines or the string "-->"

**Comment by delphiki** [comment]
That's a WIP

**Comment by delphiki** [comment]
Support has been added in version 2.3.0 : https://github.com/captioning/captioning/tree/2.3.0
