### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by hyperlogin** [captioning/captioning#30]
hi there when i load up a srt file it loads for awhile then cut off resulting in error connection any idea what's happening?

**Comment by kakaska** [comment]
hi

can you give some more info? eg. php version, os, srt file type

**Comment by hyperlogin** [comment]
PHP Version 5.5.12 , OS windows 8 64bit ,srt file type??

**Comment by kakaska** [comment]
I think the problem is in the SubripFile.php PATTERN constant. Try to remove the 'x' modifier

**Comment by hyperlogin** [comment]
whats the x modifier?

**Comment by kakaska** [comment]
you can find the doc in here http://php.net/manual/en/reference.pcre.pattern.modifiers.php

**Comment by hyperlogin** [comment]
now i got this error  Fatal error: Class 'Captioning\Format\SubripFile' not found in test.php
