### ISSUE TITLE
add TED.com format?

### ISSUE THREAD

**Issue by Oreolek** [captioning/captioning#32]
TEDTalks uses a custom subtitle JSON format:

 * [Example 1](http://www.ted.com/talks/subtitles/id/451/lang/hin)
 * [Example 2](http://www.ted.com/talks/subtitles/id/33/lang/en)

**Comment by delphiki** [comment]
Hi,

I've added Json (TED) basic support in version 2.2.0 : https://github.com/captioning/captioning/tree/2.2.0

**Comment by delphiki** [comment]
@Oreolek Any feeback?
