### ISSUE TITLE
How to get the conversion value, not save to file?

### ISSUE THREAD

**Issue by fmp777** [captioning/captioning#39]
$srt->convertTo('webvtt')->save('/tmp/test.vtt');

I'm doing something like this, but I don't want to save it to file.  I've looked but can't seem to find the method for just getting the result returned.

Is there really no method for this yet, or am I just blind?

**Comment by delphiki** [comment]
There is a method to get the file content, you can simply do this:
```php
$srt->convertTo('webvtt')->build()->getFileContent();
```

**Comment by fmp777** [comment]
K it kinda looked like it bypassed some charset logic that way?

**Comment by delphiki** [comment]
Yes, you'll get a utf-8 version of the file content, not the content with the original encoding.

**Comment by fmp777** [comment]
ok, perfect.   great project!!  thanks !!

**Comment by delphiki** [comment]
Thanks for your feedback, always appreciated! :)
