### ISSUE TITLE
Invalid .srt file when there is missing text

### ISSUE THREAD

**Issue by skrivy** [captioning/captioning#42]
Please find attached diff with failing test.

```
diff --git a/tests/Captioning/Format/SubripFileTest.php b/tests/Captioning/Format/SubripFileTest.php
index 0246e51..feb86da 100644
--- a/tests/Captioning/Format/SubripFileTest.php
+++ b/tests/Captioning/Format/SubripFileTest.php
@@ -110,4 +110,11 @@ class SubripFileTest extends \PHPUnit_Framework_TestCase
         $this->setExpectedException('\Exception', $filename.' is not a proper .srt file.');
         new SubripFile($filename);
     }
+
+    public function testEmptyTextLine()
+    {
+        $filename = __DIR__.'/../../Fixtures/empty-text-line.srt';
+        $file = new SubripFile($filename, null, false, false);
+        $this->assertInstanceOf('Captioning\Format\SubripFile', $file);
+    }
 }
diff --git a/tests/Fixtures/empty-text-line.srt b/tests/Fixtures/empty-text-line.srt
new file mode 100644
index 0000000..5327baa
--- /dev/null
+++ b/tests/Fixtures/empty-text-line.srt
@@ -0,0 +1,15 @@
+1
+00:00:01,764 --> 00:00:03,366
+Sometext 1
+
+2
+00:00:03,433 --> 00:00:04,634
+Somtext 2
+
+3
+00:00:04,701 --> 00:00:06,035
+
+
+4
+00:00:06,102 --> 00:00:07,670
+Finish the job
```

Tests execution fails:

```
PHPUnit 4.4.5-9-g5fbd35c by Sebastian Bergmann.

Configuration read from /root/captioning/phpunit.xml.dist

................E.......................

Time: 368 ms, Memory: 5.75MB

There was 1 error:

1) Captioning\Format\SubripFileTest::testEmptyLineWithText
Exception: /root/captioning/tests/Captioning/Format/../../Fixtures/empty-text-line.srt is not a proper .srt file.

/root/captioning/src/Captioning/Format/SubripFile.php:72
/root/captioning/src/Captioning/File.php:253
/root/captioning/src/Captioning/File.php:237
/root/captioning/src/Captioning/File.php:69
/root/captioning/src/Captioning/Format/SubripFile.php:63
/root/captioning/tests/Captioning/Format/SubripFileTest.php:117

FAILURES!
Tests: 40, Assertions: 84, Errors: 1.

```

**Comment by oytuntez** [comment]
We just encountered the same with a client file. Will try to mingle with regex. `_requireStrictFileFormat = false` did not help.

**Comment by skrivy** [comment]
@oytuntez FYI: We use version from merge request #45 and it seems to work. We haven't seen any issue since the merge.

**Comment by oytuntez** [comment]
Oh... It is not in master yet :( I hate maintaining our own fork with this kind of packages...

**Comment by skrivy** [comment]
I think we should encourage @delphiki to move with this project a little bit as there is no other alternative with so many supported formats. @delphiki we would love if you spent a little of your time on this project again.

**Comment by delphiki** [comment]
I'm truly sorry guys for the lack of review and updates.
Do not hesitate to remind me of all the pending PR and issues regularly, it'll force me to have a serious look into it.

**Comment by oytuntez** [comment]
No worries, @delphiki; we are already grateful that you brought this package together. I think every OS developer/maintainer needs have a maintainer buddy to balance the workload...

**Comment by delphiki** [comment]
@oytuntez Yep, if someone has the motivation to follow / review / merge, I'll be glad to consider it.

**Comment by oytuntez** [comment]
I am pushing for a new product at [MotaWord](https://www.motaword.com), if we can fit it in the roadmap, we can gladly support this library as we start using it on a daily basis. But at this moment, I don't think I can give the proper attention :( it is always better to maintain a package when you are working with it daily.

**Comment by delphiki** [comment]
This should now be fixed, thanks to @brion
