### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by garyross** [captioning/captioning#51]
SubripFile.php:105

`$errorMsg = 'Staring time invalid: ' . $subtitleTimeStart;`

Missing a 't'
Staring -> Starting

Also, it would be nice when $this->filename is empty (e.g. when using just text) to replace 
" is not a proper .srt file." with "The srt input has an error"

**Comment by hartman** [comment]
This was already fixed with 43d2a2a, but that is not yet released.

**Comment by delphiki** [comment]
Damn, sorry for the lack of updates and investment guys, I really need to find so time to review all the issues and PRs properly.
