### ISSUE TITLE
Ignore overlapping subtitle with each others

### ISSUE THREAD

**Issue by NabiKAZ** [captioning/captioning#60]
I have this SRT subtitle:

```
1
00:00:01,000 --> 00:00:02,900
sub1

2
00:00:02,100 --> 00:00:03,100
sub2
```

I know subtitle number 2 is before end of subtitle number 1, and they overlapping with each other.

But I test with many media player, and show srt good.

Here you can see first show subtitle number 1, and after it, show subtitle number 2 above of number 1:
![image](https://user-images.githubusercontent.com/246721/33156640-f52d4046-d010-11e7-839f-2dce85037bd2.png)

But I test and validate with this project and get this error:

```
try {
    
	$file = new SubripFile('111.srt');
	$cues = $file->getCues();
	
} catch(Exception $e) {
    die("Error: ".$e->getMessage()."\n");
}
```

```
Error: 111.srt is not a proper .srt file. (Starting time invalid: 00:00:02,100 at line 5)
```

Can I ignore this error and work on SRT file in force mode?

**Comment by delphiki** [comment]
I should write a bit of usage documentation, but I'll repeat the same as in your other issue:

You can disable the strict format checking when creating your SubripFile instance by setting the 4th parameter to false:
```php
$srt = new SubripFile('myfile.srt', null, false, false);
```
cf. https://github.com/captioning/captioning/blob/master/src/Captioning/Format/SubripFile.php#L35
