### ISSUE TITLE
The order of indexes does not important for me

### ISSUE THREAD

**Issue by NabiKAZ** [captioning/captioning#61]
About this part of subtitle:
```
3142
02:45:04,499 --> 02:45:08,473
sub1

3144
02:45:12,588 --> 02:45:14,456
sub2
```
And this error:
```
Error: 222.srt is not a proper .srt file. (Invalid subtitle order index: 3144 at line 13644)
```
The order of indexes or the absence of an index does not important for me.
In my opinion, this rigor is unnecessary while the players are not sensitive to this issue.
I thinks must be have any way to ignore this error and work on subtitle in force mode. (be like ticket https://github.com/captioning/captioning/issues/60)

**Comment by delphiki** [comment]
You can disabled the strict format checking when creating your SubripFile instance by setting the 4th parameter to false:
```php
$srt = new SubripFile('myfile.srt', null, false, false);
```
cf. https://github.com/captioning/captioning/blob/master/src/Captioning/Format/SubripFile.php#L35
