### ISSUE TITLE
Parsing WebVTT: Allowed memory size exhausted

### ISSUE THREAD

**Issue by miranovy** [captioning/captioning#67]
An attempt to parse this example ends a fatal error.

```php
$file = new WebvttFile(null);
$file->loadFromString("WEBVTT");
```

Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 32 bytes) in .../vendor/captioning/captioning/src/Captioning/Format/WebvttFile.php on line 51

**Comment by miranovy** [comment]
Fix is https://github.com/serverzone/captioning/pull/5

**Comment by delphiki** [comment]
Fix applied in this repo, thanks!

**Comment by delphiki** [comment]
https://github.com/captioning/captioning/commit/084acba2de8e9692ac8f198e5f170d56eea55de1
