### ISSUE TITLE
The each() function is deprecated in PHP 7.2

### ISSUE THREAD

**Issue by ShaunDychko** [captioning/captioning#72]
The `each()` function in `Captioning\File->getNextValueFromArray()` is deprecated in PHP 7.2. 
Ref: http://php.net/manual/en/function.each.php.

**Comment by istiak-tridip** [comment]
Why there is no fix yet? :(

**Comment by peter279k** [comment]
@istiak-tridip, according to [latest commit](https://github.com/captioning/captioning/commit/240b21a47aa96ae921a88e9c0faa5b6f6e9a026e) for `Captioning\File` class, this issue has been resolved.

**Comment by delphiki** [comment]
Indeed it is, thanks for the heads up! :)
