### ISSUE TITLE
Allowed memory size of 268435456 bytes exhausted (tried to allocate 134217736 bytes)

### ISSUE THREAD

**Issue by mwleinad** [captioning/captioning#74]
The VTT file is not valid, but the expected result is a non-validated file.

Trace
 Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 268435456 bytes exhausted (tried to allocate 134217736 bytes) in /usr/share/nginx/laravel/vendor/ilosvideos/captioning/src/Captioning/Format/WebvttFile.php:61
Stack trace:
#0 /usr/share/nginx/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(137): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /usr/share/nginx/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /usr/share/nginx/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /usr/share/nginx/laravel/vendor/ilosvideos/captioning/src/Captioning/File.php(253): Captioning\Format\WebvttFile->parse()
#4 /usr/share/nginx/laravel/Modules/Caption/Services/CaptionUploadService.php(137): Captioning\Format\WebvttFile->loadFromString()

Attaching file with error. (GitHub won't allow me to upload the VTT)

[CP0900253601_transcript.txt](https://github.com/captioning/captioning/files/3112798/CP0900253601_transcript.txt)

**Comment by mwleinad** [comment]
https://github.com/captioning/captioning/pull/75

**Comment by peter279k** [comment]
Since the PR #75 is merged, I think this issue can be closed.

**Comment by delphiki** [comment]
Thanks!
